### PR TITLE
Don't recreate the scene if it already exists

### PR DESCRIPTION
**Pull request by b4zz4**

### CODE REVIEW

**Comment by tin2tin** [comment]
User may benefit more from an Overwrite checkbox option, where existing similar named scenes will either be left untouched or deleted and created from scratch.

What to do with timing changes? Should timing changes be detected and how (=any text change?)? 

And how do we clean up old scenes, if users have been renaming them?

This quickly becomes quite complicated, which is why I've left it up to users to do the clean up themselves.

**Comment by b4zz4** [comment]
Not overwrite is not destructive, it only changes the times and adds objects
> What to do with timing changes? Should timing changes be detected and how (=any text change?)?

Yeah, he changes them in the original scene while he calls himself the same.

> And how do we clean up old scenes, if users have been renaming them?

Before this change it debates orphan scenes and added 001, 002, etc.
I think the users clean it when they change their name is the best choice, but to preserve the scenes with the same name works well.

**Comment by tin2tin** [comment]
I'm ok with this change if it can be done without try & except?

**Comment by b4zz4** [comment]
I think it's something like...
`if bpy.data.scenes[name] is not None: `

**Comment by b4zz4** [comment]
~~~
            if bpy.data.scenes is None:
                new_scene = bpy.data.scenes[name]
            else:
                new_scene = bpy.data.scenes.new(name=name)
~~~

**Pull request closed without merging**
